#include<iostream>
using namespace std;

int * func()
{ 
	//new返回的是该数据类型的指针
 int *p  =	new int(10);
 return p;

}
void test01()
{ 

	int* p = func();
	cout << *p << endl;
	//释放堆区 关键字delete
	/*delete p;
	cout << *p << endl;*/

}
//在堆区创建数组
void test02()
{

	int * arr = new int[10];
	for (int i = 0; i < 10; i++)
	{
		arr[i] = i + 100;//F赋值 100到109
	}
	for (int i = 0; i < 10; i++)
	{
		cout << arr[i]<< endl;
	}

}



int main()
{
	test01();
	test02();

	system("pause");
	return 0;
}
